"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class add_node_ack_t(object):
    __slots__ = ["utime", "node_type", "mu", "cov", "sensor_id"]

    NODE_POSE2D = 1
    NODE_POSE3D = 2

    def __init__(self):
        self.utime = 0
        self.node_type = 0
        self.mu = [ 0.0 for dim0 in range(6) ]
        self.cov = [ 0.0 for dim0 in range(36) ]
        self.sensor_id = 0

    def encode(self):
        buf = BytesIO()
        buf.write(add_node_ack_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qh", self.utime, self.node_type))
        buf.write(struct.pack('>6d', *self.mu[:6]))
        buf.write(struct.pack('>36d', *self.cov[:36]))
        buf.write(struct.pack(">i", self.sensor_id))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != add_node_ack_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return add_node_ack_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = add_node_ack_t()
        self.utime, self.node_type = struct.unpack(">qh", buf.read(10))
        self.mu = struct.unpack('>6d', buf.read(48))
        self.cov = struct.unpack('>36d', buf.read(288))
        self.sensor_id = struct.unpack(">i", buf.read(4))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if add_node_ack_t in parents: return 0
        tmphash = (0xa79f981a8df46a1b) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if add_node_ack_t._packed_fingerprint is None:
            add_node_ack_t._packed_fingerprint = struct.pack(">Q", add_node_ack_t._get_hash_recursive([]))
        return add_node_ack_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

