"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class save_waypoint_t(object):
    __slots__ = ["utime", "waypoint_id"]

    def __init__(self):
        self.utime = 0
        self.waypoint_id = 0

    def encode(self):
        buf = BytesIO()
        buf.write(save_waypoint_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.utime, self.waypoint_id))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != save_waypoint_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return save_waypoint_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = save_waypoint_t()
        self.utime, self.waypoint_id = struct.unpack(">qi", buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if save_waypoint_t in parents: return 0
        tmphash = (0x3c21f58199511912) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if save_waypoint_t._packed_fingerprint is None:
            save_waypoint_t._packed_fingerprint = struct.pack(">Q", save_waypoint_t._get_hash_recursive([]))
        return save_waypoint_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

