"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class color_t(object):
    __slots__ = ["r", "g", "b"]

    def __init__(self):
        self.r = 0.0
        self.g = 0.0
        self.b = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(color_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">fff", self.r, self.g, self.b))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != color_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return color_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = color_t()
        self.r, self.g, self.b = struct.unpack(">fff", buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if color_t in parents: return 0
        tmphash = (0xf914f112c253de39) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if color_t._packed_fingerprint is None:
            color_t._packed_fingerprint = struct.pack(">Q", color_t._get_hash_recursive([]))
        return color_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

