"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class carmen3d_point_cov_t(object):
    __slots__ = ["x", "xy", "y", "z", "yaw", "pitch", "roll"]

    def __init__(self):
        self.x = 0.0
        self.xy = 0.0
        self.y = 0.0
        self.z = 0.0
        self.yaw = 0.0
        self.pitch = 0.0
        self.roll = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(carmen3d_point_cov_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ddddddd", self.x, self.xy, self.y, self.z, self.yaw, self.pitch, self.roll))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != carmen3d_point_cov_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return carmen3d_point_cov_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = carmen3d_point_cov_t()
        self.x, self.xy, self.y, self.z, self.yaw, self.pitch, self.roll = struct.unpack(">ddddddd", buf.read(56))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if carmen3d_point_cov_t in parents: return 0
        tmphash = (0x5110ab1b98e9e389) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if carmen3d_point_cov_t._packed_fingerprint is None:
            carmen3d_point_cov_t._packed_fingerprint = struct.pack(">Q", carmen3d_point_cov_t._get_hash_recursive([]))
        return carmen3d_point_cov_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

