"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class nmea_t(object):
    __slots__ = ["utime", "nmea"]

    def __init__(self):
        self.utime = 0
        self.nmea = ""

    def encode(self):
        buf = BytesIO()
        buf.write(nmea_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        __nmea_encoded = self.nmea.encode('utf-8')
        buf.write(struct.pack('>I', len(__nmea_encoded)+1))
        buf.write(__nmea_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != nmea_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return nmea_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = nmea_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        __nmea_len = struct.unpack('>I', buf.read(4))[0]
        self.nmea = buf.read(__nmea_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if nmea_t in parents: return 0
        tmphash = (0xc245172bc5521f) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if nmea_t._packed_fingerprint is None:
            nmea_t._packed_fingerprint = struct.pack(">Q", nmea_t._get_hash_recursive([]))
        return nmea_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

