"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class scan_info_t(object):
    __slots__ = ["utime", "line_id", "filename", "channelname"]

    def __init__(self):
        self.utime = 0
        self.line_id = 0
        self.filename = ""
        self.channelname = ""

    def encode(self):
        buf = BytesIO()
        buf.write(scan_info_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.utime, self.line_id))
        __filename_encoded = self.filename.encode('utf-8')
        buf.write(struct.pack('>I', len(__filename_encoded)+1))
        buf.write(__filename_encoded)
        buf.write(b"\0")
        __channelname_encoded = self.channelname.encode('utf-8')
        buf.write(struct.pack('>I', len(__channelname_encoded)+1))
        buf.write(__channelname_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != scan_info_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return scan_info_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = scan_info_t()
        self.utime, self.line_id = struct.unpack(">qi", buf.read(12))
        __filename_len = struct.unpack('>I', buf.read(4))[0]
        self.filename = buf.read(__filename_len)[:-1].decode('utf-8', 'replace')
        __channelname_len = struct.unpack('>I', buf.read(4))[0]
        self.channelname = buf.read(__channelname_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if scan_info_t in parents: return 0
        tmphash = (0x8b294bc4e2f6831b) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if scan_info_t._packed_fingerprint is None:
            scan_info_t._packed_fingerprint = struct.pack(">Q", scan_info_t._get_hash_recursive([]))
        return scan_info_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

