engine:
  - prefix: "left_rear"
    position: "-2.0 1.027135 0.318237"
    orientation: "0.0 0.0 0.0"
  - prefix: "right_rear"
    position: "-2.0 -1.027135 0.318237"
    orientation: "0.0 0.0 0.0"
  - prefix: "left_front"
    position: "1.2 1.0  0.4"
    orientation: "0.0 0.0 1.5707"
  - prefix: "right_front"
    position: "1.2 -1.0 0.4"
    orientation: "0.0 0.0 -1.5707"