"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class ardrone_drive_t(object):
    __slots__ = ["utime", "vx", "vy", "vz", "vr"]

    def __init__(self):
        self.utime = 0
        self.vx = 0.0
        self.vy = 0.0
        self.vz = 0.0
        self.vr = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(ardrone_drive_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qffff", self.utime, self.vx, self.vy, self.vz, self.vr))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ardrone_drive_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ardrone_drive_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ardrone_drive_t()
        self.utime, self.vx, self.vy, self.vz, self.vr = struct.unpack(">qffff", buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if ardrone_drive_t in parents: return 0
        tmphash = (0xb816e9423d0683c1) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ardrone_drive_t._packed_fingerprint is None:
            ardrone_drive_t._packed_fingerprint = struct.pack(">Q", ardrone_drive_t._get_hash_recursive([]))
        return ardrone_drive_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

