"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class auv_mission_status_t(object):
    __slots__ = ["mission_running", "waiting_to_start"]

    def __init__(self):
        self.mission_running = False
        self.waiting_to_start = False

    def encode(self):
        buf = BytesIO()
        buf.write(auv_mission_status_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bb", self.mission_running, self.waiting_to_start))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != auv_mission_status_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return auv_mission_status_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = auv_mission_status_t()
        self.mission_running = bool(struct.unpack('b', buf.read(1))[0])
        self.waiting_to_start = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if auv_mission_status_t in parents: return 0
        tmphash = (0x97d7cb8b5920290b) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if auv_mission_status_t._packed_fingerprint is None:
            auv_mission_status_t._packed_fingerprint = struct.pack(">Q", auv_mission_status_t._get_hash_recursive([]))
        return auv_mission_status_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

