"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class auv_logger_cmd_t(object):
    __slots__ = ["utime", "type", "lcmlog_name", "camlog_dir"]

    START_LOGGING = 1
    STOP_LOGGING = 2

    def __init__(self):
        self.utime = 0
        self.type = 0
        self.lcmlog_name = ""
        self.camlog_dir = ""

    def encode(self):
        buf = BytesIO()
        buf.write(auv_logger_cmd_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.utime, self.type))
        __lcmlog_name_encoded = self.lcmlog_name.encode('utf-8')
        buf.write(struct.pack('>I', len(__lcmlog_name_encoded)+1))
        buf.write(__lcmlog_name_encoded)
        buf.write(b"\0")
        __camlog_dir_encoded = self.camlog_dir.encode('utf-8')
        buf.write(struct.pack('>I', len(__camlog_dir_encoded)+1))
        buf.write(__camlog_dir_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != auv_logger_cmd_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return auv_logger_cmd_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = auv_logger_cmd_t()
        self.utime, self.type = struct.unpack(">qi", buf.read(12))
        __lcmlog_name_len = struct.unpack('>I', buf.read(4))[0]
        self.lcmlog_name = buf.read(__lcmlog_name_len)[:-1].decode('utf-8', 'replace')
        __camlog_dir_len = struct.unpack('>I', buf.read(4))[0]
        self.camlog_dir = buf.read(__camlog_dir_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if auv_logger_cmd_t in parents: return 0
        tmphash = (0xd64c7e4b84abe1f4) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if auv_logger_cmd_t._packed_fingerprint is None:
            auv_logger_cmd_t._packed_fingerprint = struct.pack(">Q", auv_logger_cmd_t._get_hash_recursive([]))
        return auv_logger_cmd_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

