"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class auv_safety_rules_t(object):
    __slots__ = ["utime", "safety_rules_active", "safety_rules_violated"]

    SAFETY_DEPTH_CONSENSUS = 1
    SAFETY_DEPTH_TIME_CONSENSUS = 2
    SAFETY_HEADING_CONSENSUS = 4
    SAFETY_HEADING_TIME_CONSENSUS = 8

    def __init__(self):
        self.utime = 0
        self.safety_rules_active = 0
        self.safety_rules_violated = 0

    def encode(self):
        buf = BytesIO()
        buf.write(auv_safety_rules_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qqq", self.utime, self.safety_rules_active, self.safety_rules_violated))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != auv_safety_rules_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return auv_safety_rules_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = auv_safety_rules_t()
        self.utime, self.safety_rules_active, self.safety_rules_violated = struct.unpack(">qqq", buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if auv_safety_rules_t in parents: return 0
        tmphash = (0x6f015b4922c653e0) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if auv_safety_rules_t._packed_fingerprint is None:
            auv_safety_rules_t._packed_fingerprint = struct.pack(">Q", auv_safety_rules_t._get_hash_recursive([]))
        return auv_safety_rules_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

