"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import perllcm.carlab_error_t

class carlab_error_report_t(object):
    __slots__ = ["utime", "error_count", "errors"]

    def __init__(self):
        self.utime = 0
        self.error_count = 0
        self.errors = []

    def encode(self):
        buf = BytesIO()
        buf.write(carlab_error_report_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.utime, self.error_count))
        for i0 in range(self.error_count):
            assert self.errors[i0]._get_packed_fingerprint() == perllcm.carlab_error_t._get_packed_fingerprint()
            self.errors[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != carlab_error_report_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return carlab_error_report_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = carlab_error_report_t()
        self.utime, self.error_count = struct.unpack(">qi", buf.read(12))
        self.errors = []
        for i0 in range(self.error_count):
            self.errors.append(perllcm.carlab_error_t._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if carlab_error_report_t in parents: return 0
        newparents = parents + [carlab_error_report_t]
        tmphash = (0x603400c8bfe5f2e9+ perllcm.carlab_error_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if carlab_error_report_t._packed_fingerprint is None:
            carlab_error_report_t._packed_fingerprint = struct.pack(">Q", carlab_error_report_t._get_hash_recursive([]))
        return carlab_error_report_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

