"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class carlab_error_t(object):
    __slots__ = ["error_type", "error_timestamp", "error_code", "error_description"]

    TYPE_WARNING = 0
    TYPE_SERIOUS_LEVEL_1 = 1
    TYPE_SERIOUS_LEVEL_2 = 2
    TYPE_CATASTROPHIC = 3

    def __init__(self):
        self.error_type = 0
        self.error_timestamp = 0
        self.error_code = 0
        self.error_description = ""

    def encode(self):
        buf = BytesIO()
        buf.write(carlab_error_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">iqi", self.error_type, self.error_timestamp, self.error_code))
        __error_description_encoded = self.error_description.encode('utf-8')
        buf.write(struct.pack('>I', len(__error_description_encoded)+1))
        buf.write(__error_description_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != carlab_error_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return carlab_error_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = carlab_error_t()
        self.error_type, self.error_timestamp, self.error_code = struct.unpack(">iqi", buf.read(16))
        __error_description_len = struct.unpack('>I', buf.read(4))[0]
        self.error_description = buf.read(__error_description_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if carlab_error_t in parents: return 0
        tmphash = (0xc948d68f9c536705) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if carlab_error_t._packed_fingerprint is None:
            carlab_error_t._packed_fingerprint = struct.pack(">Q", carlab_error_t._get_hash_recursive([]))
        return carlab_error_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

