"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class carlab_wrench_effort_t(object):
    __slots__ = ["utime", "throttle", "steer_angle", "brakes"]

    def __init__(self):
        self.utime = 0
        self.throttle = 0.0
        self.steer_angle = 0.0
        self.brakes = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(carlab_wrench_effort_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qfff", self.utime, self.throttle, self.steer_angle, self.brakes))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != carlab_wrench_effort_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return carlab_wrench_effort_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = carlab_wrench_effort_t()
        self.utime, self.throttle, self.steer_angle, self.brakes = struct.unpack(">qfff", buf.read(20))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if carlab_wrench_effort_t in parents: return 0
        tmphash = (0x4d14f65ab4f93a44) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if carlab_wrench_effort_t._packed_fingerprint is None:
            carlab_wrench_effort_t._packed_fingerprint = struct.pack(">Q", carlab_wrench_effort_t._get_hash_recursive([]))
        return carlab_wrench_effort_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

