"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class color_byte_collection_t(object):
    __slots__ = ["n", "r", "g", "b"]

    def __init__(self):
        self.n = 0
        self.r = ""
        self.g = ""
        self.b = ""

    def encode(self):
        buf = BytesIO()
        buf.write(color_byte_collection_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.n))
        buf.write(bytearray(self.r[:self.n]))
        buf.write(bytearray(self.g[:self.n]))
        buf.write(bytearray(self.b[:self.n]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != color_byte_collection_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return color_byte_collection_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = color_byte_collection_t()
        self.n = struct.unpack(">i", buf.read(4))[0]
        self.r = buf.read(self.n)
        self.g = buf.read(self.n)
        self.b = buf.read(self.n)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if color_byte_collection_t in parents: return 0
        tmphash = (0xe8268054044c62f2) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if color_byte_collection_t._packed_fingerprint is None:
            color_byte_collection_t._packed_fingerprint = struct.pack(">Q", color_byte_collection_t._get_hash_recursive([]))
        return color_byte_collection_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

