"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class est_navigator_debug_meas_t(object):
    __slots__ = ["utime", "id_str", "meas_len", "nu", "z", "nis", "mahal_innov_passed"]

    def __init__(self):
        self.utime = 0
        self.id_str = ""
        self.meas_len = 0
        self.nu = []
        self.z = []
        self.nis = 0.0
        self.mahal_innov_passed = 0

    def encode(self):
        buf = BytesIO()
        buf.write(est_navigator_debug_meas_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        __id_str_encoded = self.id_str.encode('utf-8')
        buf.write(struct.pack('>I', len(__id_str_encoded)+1))
        buf.write(__id_str_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">i", self.meas_len))
        buf.write(struct.pack('>%dd' % self.meas_len, *self.nu[:self.meas_len]))
        buf.write(struct.pack('>%dd' % self.meas_len, *self.z[:self.meas_len]))
        buf.write(struct.pack(">db", self.nis, self.mahal_innov_passed))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != est_navigator_debug_meas_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return est_navigator_debug_meas_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = est_navigator_debug_meas_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        __id_str_len = struct.unpack('>I', buf.read(4))[0]
        self.id_str = buf.read(__id_str_len)[:-1].decode('utf-8', 'replace')
        self.meas_len = struct.unpack(">i", buf.read(4))[0]
        self.nu = struct.unpack('>%dd' % self.meas_len, buf.read(self.meas_len * 8))
        self.z = struct.unpack('>%dd' % self.meas_len, buf.read(self.meas_len * 8))
        self.nis, self.mahal_innov_passed = struct.unpack(">db", buf.read(9))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if est_navigator_debug_meas_t in parents: return 0
        tmphash = (0xac4c59588563f95) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if est_navigator_debug_meas_t._packed_fingerprint is None:
            est_navigator_debug_meas_t._packed_fingerprint = struct.pack(">Q", est_navigator_debug_meas_t._get_hash_recursive([]))
        return est_navigator_debug_meas_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

