"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class est_navigator_debug_pred_t(object):
    __slots__ = ["utime", "dt"]

    def __init__(self):
        self.utime = 0
        self.dt = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(est_navigator_debug_pred_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qd", self.utime, self.dt))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != est_navigator_debug_pred_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return est_navigator_debug_pred_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = est_navigator_debug_pred_t()
        self.utime, self.dt = struct.unpack(">qd", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if est_navigator_debug_pred_t in parents: return 0
        tmphash = (0x447369c4330d1364) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if est_navigator_debug_pred_t._packed_fingerprint is None:
            est_navigator_debug_pred_t._packed_fingerprint = struct.pack(">Q", est_navigator_debug_pred_t._get_hash_recursive([]))
        return est_navigator_debug_pred_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

