"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class lb3_timestamp_t(object):
    __slots__ = ["utime", "wtime", "mytime", "frame"]

    def __init__(self):
        self.utime = 0
        self.wtime = 0
        self.mytime = 0
        self.frame = 0

    def encode(self):
        buf = BytesIO()
        buf.write(lb3_timestamp_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qqqq", self.utime, self.wtime, self.mytime, self.frame))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lb3_timestamp_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lb3_timestamp_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = lb3_timestamp_t()
        self.utime, self.wtime, self.mytime, self.frame = struct.unpack(">qqqq", buf.read(32))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if lb3_timestamp_t in parents: return 0
        tmphash = (0x17533568ee2f5334) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if lb3_timestamp_t._packed_fingerprint is None:
            lb3_timestamp_t._packed_fingerprint = struct.pack(">Q", lb3_timestamp_t._get_hash_recursive([]))
        return lb3_timestamp_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

