"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class matrix_d_t(object):
    __slots__ = ["nrows", "ncols", "n", "data"]

    def __init__(self):
        self.nrows = 0
        self.ncols = 0
        self.n = 0
        self.data = []

    def encode(self):
        buf = BytesIO()
        buf.write(matrix_d_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">iii", self.nrows, self.ncols, self.n))
        buf.write(struct.pack('>%dd' % self.n, *self.data[:self.n]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != matrix_d_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return matrix_d_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = matrix_d_t()
        self.nrows, self.ncols, self.n = struct.unpack(">iii", buf.read(12))
        self.data = struct.unpack('>%dd' % self.n, buf.read(self.n * 8))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if matrix_d_t in parents: return 0
        tmphash = (0xd4515d006e262beb) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if matrix_d_t._packed_fingerprint is None:
            matrix_d_t._packed_fingerprint = struct.pack(">Q", matrix_d_t._get_hash_recursive([]))
        return matrix_d_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

