"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class pose2d_t(object):
    __slots__ = ["utime", "mu", "Sigma"]

    def __init__(self):
        self.utime = 0
        self.mu = [ 0.0 for dim0 in range(3) ]
        self.Sigma = [ 0.0 for dim0 in range(9) ]

    def encode(self):
        buf = BytesIO()
        buf.write(pose2d_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        buf.write(struct.pack('>3d', *self.mu[:3]))
        buf.write(struct.pack('>9d', *self.Sigma[:9]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != pose2d_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return pose2d_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = pose2d_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.mu = struct.unpack('>3d', buf.read(24))
        self.Sigma = struct.unpack('>9d', buf.read(72))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if pose2d_t in parents: return 0
        tmphash = (0xb0a4f8ebe39650e0) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if pose2d_t._packed_fingerprint is None:
            pose2d_t._packed_fingerprint = struct.pack(">Q", pose2d_t._get_hash_recursive([]))
        return pose2d_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

