"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import perllcm.pvn_eview_map_exemplar_t

import perllcm.pose3d_t

class pvn_eview_map_neighborhood_t(object):
    __slots__ = ["id", "pose", "ne", "exemplars"]

    def __init__(self):
        self.id = 0
        self.pose = perllcm.pose3d_t()
        self.ne = 0
        self.exemplars = []

    def encode(self):
        buf = BytesIO()
        buf.write(pvn_eview_map_neighborhood_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.id))
        assert self.pose._get_packed_fingerprint() == perllcm.pose3d_t._get_packed_fingerprint()
        self.pose._encode_one(buf)
        buf.write(struct.pack(">i", self.ne))
        for i0 in range(self.ne):
            assert self.exemplars[i0]._get_packed_fingerprint() == perllcm.pvn_eview_map_exemplar_t._get_packed_fingerprint()
            self.exemplars[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != pvn_eview_map_neighborhood_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return pvn_eview_map_neighborhood_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = pvn_eview_map_neighborhood_t()
        self.id = struct.unpack(">q", buf.read(8))[0]
        self.pose = perllcm.pose3d_t._decode_one(buf)
        self.ne = struct.unpack(">i", buf.read(4))[0]
        self.exemplars = []
        for i0 in range(self.ne):
            self.exemplars.append(perllcm.pvn_eview_map_exemplar_t._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if pvn_eview_map_neighborhood_t in parents: return 0
        newparents = parents + [pvn_eview_map_neighborhood_t]
        tmphash = (0x7b950bdb767c6a91+ perllcm.pose3d_t._get_hash_recursive(newparents)+ perllcm.pvn_eview_map_exemplar_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if pvn_eview_map_neighborhood_t._packed_fingerprint is None:
            pvn_eview_map_neighborhood_t._packed_fingerprint = struct.pack(">Q", pvn_eview_map_neighborhood_t._get_hash_recursive([]))
        return pvn_eview_map_neighborhood_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

