"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import perllcm.pvn_eview_map_predict_data_t

class pvn_eview_map_predict_data_collection_t(object):
    __slots__ = ["n", "predict_data"]

    def __init__(self):
        self.n = 0
        self.predict_data = []

    def encode(self):
        buf = BytesIO()
        buf.write(pvn_eview_map_predict_data_collection_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.n))
        for i0 in range(self.n):
            assert self.predict_data[i0]._get_packed_fingerprint() == perllcm.pvn_eview_map_predict_data_t._get_packed_fingerprint()
            self.predict_data[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != pvn_eview_map_predict_data_collection_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return pvn_eview_map_predict_data_collection_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = pvn_eview_map_predict_data_collection_t()
        self.n = struct.unpack(">i", buf.read(4))[0]
        self.predict_data = []
        for i0 in range(self.n):
            self.predict_data.append(perllcm.pvn_eview_map_predict_data_t._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if pvn_eview_map_predict_data_collection_t in parents: return 0
        newparents = parents + [pvn_eview_map_predict_data_collection_t]
        tmphash = (0x700fd35ea2f722a8+ perllcm.pvn_eview_map_predict_data_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if pvn_eview_map_predict_data_collection_t._packed_fingerprint is None:
            pvn_eview_map_predict_data_collection_t._packed_fingerprint = struct.pack(">Q", pvn_eview_map_predict_data_collection_t._get_hash_recursive([]))
        return pvn_eview_map_predict_data_collection_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

