"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import perllcm.pose3d_t

class relative_pose_link_t(object):
    __slots__ = ["idx0", "idx1", "pose"]

    def __init__(self):
        self.idx0 = 0
        self.idx1 = 0
        self.pose = perllcm.pose3d_t()

    def encode(self):
        buf = BytesIO()
        buf.write(relative_pose_link_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ii", self.idx0, self.idx1))
        assert self.pose._get_packed_fingerprint() == perllcm.pose3d_t._get_packed_fingerprint()
        self.pose._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != relative_pose_link_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return relative_pose_link_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = relative_pose_link_t()
        self.idx0, self.idx1 = struct.unpack(">ii", buf.read(8))
        self.pose = perllcm.pose3d_t._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if relative_pose_link_t in parents: return 0
        newparents = parents + [relative_pose_link_t]
        tmphash = (0xc3cd47cab28e44c9+ perllcm.pose3d_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if relative_pose_link_t._packed_fingerprint is None:
            relative_pose_link_t._packed_fingerprint = struct.pack(">Q", relative_pose_link_t._get_hash_recursive([]))
        return relative_pose_link_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

