"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class segway_drive_t(object):
    __slots__ = ["utime", "vt", "vr"]

    def __init__(self):
        self.utime = 0
        self.vt = 0.0
        self.vr = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(segway_drive_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qff", self.utime, self.vt, self.vr))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != segway_drive_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return segway_drive_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = segway_drive_t()
        self.utime, self.vt, self.vr = struct.unpack(">qff", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if segway_drive_t in parents: return 0
        tmphash = (0xa32de1f8680559fa) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if segway_drive_t._packed_fingerprint is None:
            segway_drive_t._packed_fingerprint = struct.pack(">Q", segway_drive_t._get_hash_recursive([]))
        return segway_drive_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

