"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import perllcm.tag_detection_t

class tag_detection_collection_t(object):
    __slots__ = ["utime", "ndetections", "detections"]

    def __init__(self):
        self.utime = 0
        self.ndetections = 0
        self.detections = []

    def encode(self):
        buf = BytesIO()
        buf.write(tag_detection_collection_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.utime, self.ndetections))
        for i0 in range(self.ndetections):
            assert self.detections[i0]._get_packed_fingerprint() == perllcm.tag_detection_t._get_packed_fingerprint()
            self.detections[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != tag_detection_collection_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return tag_detection_collection_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = tag_detection_collection_t()
        self.utime, self.ndetections = struct.unpack(">qi", buf.read(12))
        self.detections = []
        for i0 in range(self.ndetections):
            self.detections.append(perllcm.tag_detection_t._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if tag_detection_collection_t in parents: return 0
        newparents = parents + [tag_detection_collection_t]
        tmphash = (0x6ca4f4b29f746fa2+ perllcm.tag_detection_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if tag_detection_collection_t._packed_fingerprint is None:
            tag_detection_collection_t._packed_fingerprint = struct.pack(">Q", tag_detection_collection_t._get_hash_recursive([]))
        return tag_detection_collection_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

