"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class van_siftgpu_params_t(object):
    __slots__ = ["utime", "dogThreshold", "edgeThreshold", "dogLevels", "filterWidthFactor", "orientWindowFactor", "gridSizeFactor"]

    def __init__(self):
        self.utime = 0
        self.dogThreshold = 0.0
        self.edgeThreshold = 0.0
        self.dogLevels = 0
        self.filterWidthFactor = 0.0
        self.orientWindowFactor = 0.0
        self.gridSizeFactor = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(van_siftgpu_params_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qddiddd", self.utime, self.dogThreshold, self.edgeThreshold, self.dogLevels, self.filterWidthFactor, self.orientWindowFactor, self.gridSizeFactor))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != van_siftgpu_params_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return van_siftgpu_params_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = van_siftgpu_params_t()
        self.utime, self.dogThreshold, self.edgeThreshold, self.dogLevels, self.filterWidthFactor, self.orientWindowFactor, self.gridSizeFactor = struct.unpack(">qddiddd", buf.read(52))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if van_siftgpu_params_t in parents: return 0
        tmphash = (0x762368f77745a6d1) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if van_siftgpu_params_t._packed_fingerprint is None:
            van_siftgpu_params_t._packed_fingerprint = struct.pack(">Q", van_siftgpu_params_t._get_hash_recursive([]))
        return van_siftgpu_params_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

