"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class van_feature_user_depth_t(object):
    __slots__ = ["npts", "mu_Z", "Sigma_Z"]

    def __init__(self):
        self.npts = 0
        self.mu_Z = []
        self.Sigma_Z = []

    def encode(self):
        buf = BytesIO()
        buf.write(van_feature_user_depth_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.npts))
        buf.write(struct.pack('>%df' % self.npts, *self.mu_Z[:self.npts]))
        buf.write(struct.pack('>%df' % self.npts, *self.Sigma_Z[:self.npts]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != van_feature_user_depth_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return van_feature_user_depth_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = van_feature_user_depth_t()
        self.npts = struct.unpack(">i", buf.read(4))[0]
        self.mu_Z = struct.unpack('>%df' % self.npts, buf.read(self.npts * 4))
        self.Sigma_Z = struct.unpack('>%df' % self.npts, buf.read(self.npts * 4))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if van_feature_user_depth_t in parents: return 0
        tmphash = (0x377665798924fe99) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if van_feature_user_depth_t._packed_fingerprint is None:
            van_feature_user_depth_t._packed_fingerprint = struct.pack(">Q", van_feature_user_depth_t._get_hash_recursive([]))
        return van_feature_user_depth_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

