"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import perllcm.van_vlink_t

class van_vlink_collection_t(object):
    __slots__ = ["nlinks", "vlink"]

    def __init__(self):
        self.nlinks = 0
        self.vlink = []

    def encode(self):
        buf = BytesIO()
        buf.write(van_vlink_collection_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.nlinks))
        for i0 in range(self.nlinks):
            assert self.vlink[i0]._get_packed_fingerprint() == perllcm.van_vlink_t._get_packed_fingerprint()
            self.vlink[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != van_vlink_collection_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return van_vlink_collection_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = van_vlink_collection_t()
        self.nlinks = struct.unpack(">i", buf.read(4))[0]
        self.vlink = []
        for i0 in range(self.nlinks):
            self.vlink.append(perllcm.van_vlink_t._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if van_vlink_collection_t in parents: return 0
        newparents = parents + [van_vlink_collection_t]
        tmphash = (0x2338887955f0e8a0+ perllcm.van_vlink_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if van_vlink_collection_t._packed_fingerprint is None:
            van_vlink_collection_t._packed_fingerprint = struct.pack(">Q", van_vlink_collection_t._get_hash_recursive([]))
        return van_vlink_collection_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

