"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import perllcm.pose3d_t

class van_plink_t(object):
    __slots__ = ["utime_i", "utime_j", "prior", "x_ji", "link_id", "Ig", "S_L", "dynamic_xvs", "x_vs1", "x_vs2"]

    def __init__(self):
        self.utime_i = 0
        self.utime_j = 0
        self.prior = False
        self.x_ji = perllcm.pose3d_t()
        self.link_id = 0
        self.Ig = 0.0
        self.S_L = 0.0
        self.dynamic_xvs = False
        self.x_vs1 = [ 0.0 for dim0 in range(6) ]
        self.x_vs2 = [ 0.0 for dim0 in range(6) ]

    def encode(self):
        buf = BytesIO()
        buf.write(van_plink_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qqb", self.utime_i, self.utime_j, self.prior))
        assert self.x_ji._get_packed_fingerprint() == perllcm.pose3d_t._get_packed_fingerprint()
        self.x_ji._encode_one(buf)
        buf.write(struct.pack(">iddb", self.link_id, self.Ig, self.S_L, self.dynamic_xvs))
        buf.write(struct.pack('>6d', *self.x_vs1[:6]))
        buf.write(struct.pack('>6d', *self.x_vs2[:6]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != van_plink_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return van_plink_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = van_plink_t()
        self.utime_i, self.utime_j = struct.unpack(">qq", buf.read(16))
        self.prior = bool(struct.unpack('b', buf.read(1))[0])
        self.x_ji = perllcm.pose3d_t._decode_one(buf)
        self.link_id, self.Ig, self.S_L = struct.unpack(">idd", buf.read(20))
        self.dynamic_xvs = bool(struct.unpack('b', buf.read(1))[0])
        self.x_vs1 = struct.unpack('>6d', buf.read(48))
        self.x_vs2 = struct.unpack('>6d', buf.read(48))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if van_plink_t in parents: return 0
        newparents = parents + [van_plink_t]
        tmphash = (0x2c0d6c526917c024+ perllcm.pose3d_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if van_plink_t._packed_fingerprint is None:
            van_plink_t._packed_fingerprint = struct.pack(">Q", van_plink_t._get_hash_recursive([]))
        return van_plink_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

