"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class vis_cvu_map_t(object):
    __slots__ = ["width", "height", "size", "mapu", "mapv"]

    def __init__(self):
        self.width = 0
        self.height = 0
        self.size = 0
        self.mapu = []
        self.mapv = []

    def encode(self):
        buf = BytesIO()
        buf.write(vis_cvu_map_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">hhi", self.width, self.height, self.size))
        buf.write(struct.pack('>%df' % self.size, *self.mapu[:self.size]))
        buf.write(struct.pack('>%df' % self.size, *self.mapv[:self.size]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != vis_cvu_map_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return vis_cvu_map_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = vis_cvu_map_t()
        self.width, self.height, self.size = struct.unpack(">hhi", buf.read(8))
        self.mapu = struct.unpack('>%df' % self.size, buf.read(self.size * 4))
        self.mapv = struct.unpack('>%df' % self.size, buf.read(self.size * 4))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if vis_cvu_map_t in parents: return 0
        tmphash = (0x90034708ce4244a4) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if vis_cvu_map_t._packed_fingerprint is None:
            vis_cvu_map_t._packed_fingerprint = struct.pack(">Q", vis_cvu_map_t._get_hash_recursive([]))
        return vis_cvu_map_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

