"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class bs_cnv_t(object):
    __slots__ = ["time_received", "time_nav", "x", "y", "z", "heading"]

    def __init__(self):
        self.time_received = 0
        self.time_nav = 0
        self.x = 0.0
        self.y = 0.0
        self.z = 0.0
        self.heading = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(bs_cnv_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qqdddd", self.time_received, self.time_nav, self.x, self.y, self.z, self.heading))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != bs_cnv_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return bs_cnv_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = bs_cnv_t()
        self.time_received, self.time_nav, self.x, self.y, self.z, self.heading = struct.unpack(">qqdddd", buf.read(48))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if bs_cnv_t in parents: return 0
        tmphash = (0x5887d493709dc474) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if bs_cnv_t._packed_fingerprint is None:
            bs_cnv_t._packed_fingerprint = struct.pack(">Q", bs_cnv_t._get_hash_recursive([]))
        return bs_cnv_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

