"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class bs_dvl_2_t(object):
    __slots__ = ["time_received", "time", "velocity1", "velocity2", "velocity3", "velocity4", "range1", "range2", "range3", "range4", "temperature", "time_measured"]

    def __init__(self):
        self.time_received = 0
        self.time = 0
        self.velocity1 = 0.0
        self.velocity2 = 0.0
        self.velocity3 = 0.0
        self.velocity4 = 0.0
        self.range1 = 0.0
        self.range2 = 0.0
        self.range3 = 0.0
        self.range4 = 0.0
        self.temperature = 0.0
        self.time_measured = 0

    def encode(self):
        buf = BytesIO()
        buf.write(bs_dvl_2_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qqdddddddddq", self.time_received, self.time, self.velocity1, self.velocity2, self.velocity3, self.velocity4, self.range1, self.range2, self.range3, self.range4, self.temperature, self.time_measured))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != bs_dvl_2_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return bs_dvl_2_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = bs_dvl_2_t()
        self.time_received, self.time, self.velocity1, self.velocity2, self.velocity3, self.velocity4, self.range1, self.range2, self.range3, self.range4, self.temperature, self.time_measured = struct.unpack(">qqdddddddddq", buf.read(96))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if bs_dvl_2_t in parents: return 0
        tmphash = (0x7b1c3f8e759facfb) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if bs_dvl_2_t._packed_fingerprint is None:
            bs_dvl_2_t._packed_fingerprint = struct.pack(">Q", bs_dvl_2_t._get_hash_recursive([]))
        return bs_dvl_2_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

