"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class bs_nvr_t(object):
    __slots__ = ["time_received", "time", "east_velocity", "north_velocity", "down_velocity", "pitch_rate", "roll_rate", "yaw_rate"]

    def __init__(self):
        self.time_received = 0
        self.time = 0
        self.east_velocity = 0.0
        self.north_velocity = 0.0
        self.down_velocity = 0.0
        self.pitch_rate = 0.0
        self.roll_rate = 0.0
        self.yaw_rate = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(bs_nvr_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qqdddddd", self.time_received, self.time, self.east_velocity, self.north_velocity, self.down_velocity, self.pitch_rate, self.roll_rate, self.yaw_rate))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != bs_nvr_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return bs_nvr_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = bs_nvr_t()
        self.time_received, self.time, self.east_velocity, self.north_velocity, self.down_velocity, self.pitch_rate, self.roll_rate, self.yaw_rate = struct.unpack(">qqdddddd", buf.read(64))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if bs_nvr_t in parents: return 0
        tmphash = (0x110ead38a77713b5) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if bs_nvr_t._packed_fingerprint is None:
            bs_nvr_t._packed_fingerprint = struct.pack(">Q", bs_nvr_t._get_hash_recursive([]))
        return bs_nvr_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

