"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class bs_rnv_2_t(object):
    __slots__ = ["time_received", "time", "horizontal", "vertical", "distance", "heading", "depth", "absheading", "absroll", "abspitch", "time_nav"]

    def __init__(self):
        self.time_received = 0
        self.time = 0
        self.horizontal = 0.0
        self.vertical = 0.0
        self.distance = 0.0
        self.heading = 0.0
        self.depth = 0.0
        self.absheading = 0.0
        self.absroll = 0.0
        self.abspitch = 0.0
        self.time_nav = 0

    def encode(self):
        buf = BytesIO()
        buf.write(bs_rnv_2_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qqddddddddq", self.time_received, self.time, self.horizontal, self.vertical, self.distance, self.heading, self.depth, self.absheading, self.absroll, self.abspitch, self.time_nav))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != bs_rnv_2_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return bs_rnv_2_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = bs_rnv_2_t()
        self.time_received, self.time, self.horizontal, self.vertical, self.distance, self.heading, self.depth, self.absheading, self.absroll, self.abspitch, self.time_nav = struct.unpack(">qqddddddddq", buf.read(88))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if bs_rnv_2_t in parents: return 0
        tmphash = (0x4e7e9db68f6943cb) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if bs_rnv_2_t._packed_fingerprint is None:
            bs_rnv_2_t._packed_fingerprint = struct.pack(">Q", bs_rnv_2_t._get_hash_recursive([]))
        return bs_rnv_2_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

