"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class didson_raw_t(object):
    __slots__ = ["time_received", "length", "data"]

    def __init__(self):
        self.time_received = 0
        self.length = 0
        self.data = ""

    def encode(self):
        buf = BytesIO()
        buf.write(didson_raw_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.time_received, self.length))
        buf.write(bytearray(self.data[:self.length]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != didson_raw_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return didson_raw_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = didson_raw_t()
        self.time_received, self.length = struct.unpack(">qi", buf.read(12))
        self.data = buf.read(self.length)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if didson_raw_t in parents: return 0
        tmphash = (0xed3d869151ec8de3) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if didson_raw_t._packed_fingerprint is None:
            didson_raw_t._packed_fingerprint = struct.pack(">Q", didson_raw_t._get_hash_recursive([]))
        return didson_raw_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

