"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class pl_rns_t(object):
    __slots__ = ["time", "x", "y", "bearing_offset"]

    def __init__(self):
        self.time = 0
        self.x = 0.0
        self.y = 0.0
        self.bearing_offset = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(pl_rns_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qddd", self.time, self.x, self.y, self.bearing_offset))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != pl_rns_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return pl_rns_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = pl_rns_t()
        self.time, self.x, self.y, self.bearing_offset = struct.unpack(">qddd", buf.read(32))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if pl_rns_t in parents: return 0
        tmphash = (0x1d2a78ebf57ac153) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if pl_rns_t._packed_fingerprint is None:
            pl_rns_t._packed_fingerprint = struct.pack(">Q", pl_rns_t._get_hash_recursive([]))
        return pl_rns_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

