"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class pl_san_t(object):
    __slots__ = ["time", "angle"]

    def __init__(self):
        self.time = 0
        self.angle = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(pl_san_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qd", self.time, self.angle))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != pl_san_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return pl_san_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = pl_san_t()
        self.time, self.angle = struct.unpack(">qd", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if pl_san_t in parents: return 0
        tmphash = (0x75d2c4dccb690b3) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if pl_san_t._packed_fingerprint is None:
            pl_san_t._packed_fingerprint = struct.pack(">Q", pl_san_t._get_hash_recursive([]))
        return pl_san_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

