"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class pl_sus_t(object):
    __slots__ = ["time"]

    def __init__(self):
        self.time = 0

    def encode(self):
        buf = BytesIO()
        buf.write(pl_sus_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.time))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != pl_sus_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return pl_sus_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = pl_sus_t()
        self.time = struct.unpack(">q", buf.read(8))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if pl_sus_t in parents: return 0
        tmphash = (0x165e7d1f073a791f) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if pl_sus_t._packed_fingerprint is None:
            pl_sus_t._packed_fingerprint = struct.pack(">Q", pl_sus_t._get_hash_recursive([]))
        return pl_sus_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

