"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class vehicle_plan_t(object):
    __slots__ = ["time", "stop", "holdStation", "heading", "broadcast", "headingOffset", "depth", "npoints", "waypoints"]

    def __init__(self):
        self.time = 0
        self.stop = False
        self.holdStation = False
        self.heading = False
        self.broadcast = False
        self.headingOffset = 0.0
        self.depth = 0.0
        self.npoints = 0
        self.waypoints = []

    def encode(self):
        buf = BytesIO()
        buf.write(vehicle_plan_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qbbbbddi", self.time, self.stop, self.holdStation, self.heading, self.broadcast, self.headingOffset, self.depth, self.npoints))
        for i0 in range(self.npoints):
            buf.write(struct.pack('>2d', *self.waypoints[i0][:2]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != vehicle_plan_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return vehicle_plan_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = vehicle_plan_t()
        self.time = struct.unpack(">q", buf.read(8))[0]
        self.stop = bool(struct.unpack('b', buf.read(1))[0])
        self.holdStation = bool(struct.unpack('b', buf.read(1))[0])
        self.heading = bool(struct.unpack('b', buf.read(1))[0])
        self.broadcast = bool(struct.unpack('b', buf.read(1))[0])
        self.headingOffset, self.depth, self.npoints = struct.unpack(">ddi", buf.read(20))
        self.waypoints = []
        for i0 in range(self.npoints):
            self.waypoints.append(struct.unpack('>2d', buf.read(16)))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if vehicle_plan_t in parents: return 0
        tmphash = (0x50c17ab2e1957930) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if vehicle_plan_t._packed_fingerprint is None:
            vehicle_plan_t._packed_fingerprint = struct.pack(">Q", vehicle_plan_t._get_hash_recursive([]))
        return vehicle_plan_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

