"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class wp_goto_t(object):
    __slots__ = ["mode", "utime_target"]

    MODE_OFF = 0
    MODE_GOTO = 1
    MODE_RESUME = 2
    MODE_GOTO_REL = 3

    def __init__(self):
        self.mode = 0
        self.utime_target = 0

    def encode(self):
        buf = BytesIO()
        buf.write(wp_goto_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">iq", self.mode, self.utime_target))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != wp_goto_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return wp_goto_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = wp_goto_t()
        self.mode, self.utime_target = struct.unpack(">iq", buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if wp_goto_t in parents: return 0
        tmphash = (0xc52c3378aa82e234) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if wp_goto_t._packed_fingerprint is None:
            wp_goto_t._packed_fingerprint = struct.pack(">Q", wp_goto_t._get_hash_recursive([]))
        return wp_goto_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

