"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class wp_list_t(object):
    __slots__ = ["n", "id", "utime"]

    def __init__(self):
        self.n = 0
        self.id = []
        self.utime = []

    def encode(self):
        buf = BytesIO()
        buf.write(wp_list_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.n))
        buf.write(struct.pack('>%di' % self.n, *self.id[:self.n]))
        buf.write(struct.pack('>%dq' % self.n, *self.utime[:self.n]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != wp_list_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return wp_list_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = wp_list_t()
        self.n = struct.unpack(">i", buf.read(4))[0]
        self.id = struct.unpack('>%di' % self.n, buf.read(self.n * 4))
        self.utime = struct.unpack('>%dq' % self.n, buf.read(self.n * 8))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if wp_list_t in parents: return 0
        tmphash = (0x587b64826fd24565) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if wp_list_t._packed_fingerprint is None:
            wp_list_t._packed_fingerprint = struct.pack(">Q", wp_list_t._get_hash_recursive([]))
        return wp_list_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

