"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class aanderaa_4319_t(object):
    __slots__ = ["utime", "temperature", "conductivity", "salinity", "density", "speed"]

    def __init__(self):
        self.utime = 0
        self.temperature = 0.0
        self.conductivity = 0.0
        self.salinity = 0.0
        self.density = 0.0
        self.speed = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(aanderaa_4319_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qddddd", self.utime, self.temperature, self.conductivity, self.salinity, self.density, self.speed))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != aanderaa_4319_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return aanderaa_4319_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = aanderaa_4319_t()
        self.utime, self.temperature, self.conductivity, self.salinity, self.density, self.speed = struct.unpack(">qddddd", buf.read(48))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if aanderaa_4319_t in parents: return 0
        tmphash = (0x93dec935b61bdd55) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if aanderaa_4319_t._packed_fingerprint is None:
            aanderaa_4319_t._packed_fingerprint = struct.pack(">Q", aanderaa_4319_t._get_hash_recursive([]))
        return aanderaa_4319_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

