"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class acfr_psu_type_1_t(object):
    __slots__ = ["utime", "address", "voltage", "current", "temperature", "voltage_max", "current_max", "voltage_min", "current_min"]

    def __init__(self):
        self.utime = 0
        self.address = 0
        self.voltage = 0.0
        self.current = 0.0
        self.temperature = 0.0
        self.voltage_max = 0.0
        self.current_max = 0.0
        self.voltage_min = 0.0
        self.current_min = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(acfr_psu_type_1_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qbddddddd", self.utime, self.address, self.voltage, self.current, self.temperature, self.voltage_max, self.current_max, self.voltage_min, self.current_min))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != acfr_psu_type_1_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return acfr_psu_type_1_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = acfr_psu_type_1_t()
        self.utime, self.address, self.voltage, self.current, self.temperature, self.voltage_max, self.current_max, self.voltage_min, self.current_min = struct.unpack(">qbddddddd", buf.read(65))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if acfr_psu_type_1_t in parents: return 0
        tmphash = (0xee325898570315ed) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if acfr_psu_type_1_t._packed_fingerprint is None:
            acfr_psu_type_1_t._packed_fingerprint = struct.pack(">Q", acfr_psu_type_1_t._get_hash_recursive([]))
        return acfr_psu_type_1_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

