"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class ahrs_t(object):
    __slots__ = ["utime", "mtime", "roll", "pitch", "heading"]

    def __init__(self):
        self.utime = 0
        self.mtime = 0
        self.roll = 0.0
        self.pitch = 0.0
        self.heading = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(ahrs_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qqddd", self.utime, self.mtime, self.roll, self.pitch, self.heading))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ahrs_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ahrs_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ahrs_t()
        self.utime, self.mtime, self.roll, self.pitch, self.heading = struct.unpack(">qqddd", buf.read(40))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if ahrs_t in parents: return 0
        tmphash = (0x82586c97b03cfebf) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ahrs_t._packed_fingerprint is None:
            ahrs_t._packed_fingerprint = struct.pack(">Q", ahrs_t._get_hash_recursive([]))
        return ahrs_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

