"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class deltat_ping_t(object):
    __slots__ = ["utime", "count", "size", "ping"]

    def __init__(self):
        self.utime = 0
        self.count = 0
        self.size = 0
        self.ping = ""

    def encode(self):
        buf = BytesIO()
        buf.write(deltat_ping_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qih", self.utime, self.count, self.size))
        buf.write(bytearray(self.ping[:self.size]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != deltat_ping_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return deltat_ping_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = deltat_ping_t()
        self.utime, self.count, self.size = struct.unpack(">qih", buf.read(14))
        self.ping = buf.read(self.size)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if deltat_ping_t in parents: return 0
        tmphash = (0x622071afc0e0003b) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if deltat_ping_t._packed_fingerprint is None:
            deltat_ping_t._packed_fingerprint = struct.pack(">Q", deltat_ping_t._get_hash_recursive([]))
        return deltat_ping_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

