"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class evologics_ping_control_t(object):
    __slots__ = ["utime", "target_id", "send_pings", "send_fixes", "ping_rate"]

    def __init__(self):
        self.utime = 0
        self.target_id = 0
        self.send_pings = False
        self.send_fixes = False
        self.ping_rate = 0

    def encode(self):
        buf = BytesIO()
        buf.write(evologics_ping_control_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qbbbh", self.utime, self.target_id, self.send_pings, self.send_fixes, self.ping_rate))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != evologics_ping_control_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return evologics_ping_control_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = evologics_ping_control_t()
        self.utime, self.target_id = struct.unpack(">qb", buf.read(9))
        self.send_pings = bool(struct.unpack('b', buf.read(1))[0])
        self.send_fixes = bool(struct.unpack('b', buf.read(1))[0])
        self.ping_rate = struct.unpack(">h", buf.read(2))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if evologics_ping_control_t in parents: return 0
        tmphash = (0x969c49f4eed0778d) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if evologics_ping_control_t._packed_fingerprint is None:
            evologics_ping_control_t._packed_fingerprint = struct.pack(">Q", evologics_ping_control_t._get_hash_recursive([]))
        return evologics_ping_control_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

