"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class evologics_modem_t(object):
    __slots__ = ["utime", "size", "data"]

    def __init__(self):
        self.utime = 0
        self.size = 0
        self.data = ""

    def encode(self):
        buf = BytesIO()
        buf.write(evologics_modem_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.utime, self.size))
        buf.write(bytearray(self.data[:self.size]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != evologics_modem_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return evologics_modem_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = evologics_modem_t()
        self.utime, self.size = struct.unpack(">qi", buf.read(12))
        self.data = buf.read(self.size)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if evologics_modem_t in parents: return 0
        tmphash = (0x6622163ed1a7984d) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if evologics_modem_t._packed_fingerprint is None:
            evologics_modem_t._packed_fingerprint = struct.pack(">Q", evologics_modem_t._get_hash_recursive([]))
        return evologics_modem_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

