"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class ford_velodyne_t(object):
    __slots__ = ["utime", "datalen", "data"]

    def __init__(self):
        self.utime = 0
        self.datalen = 0
        self.data = ""

    def encode(self):
        buf = BytesIO()
        buf.write(ford_velodyne_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.utime, self.datalen))
        buf.write(bytearray(self.data[:self.datalen]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ford_velodyne_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ford_velodyne_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ford_velodyne_t()
        self.utime, self.datalen = struct.unpack(">qi", buf.read(12))
        self.data = buf.read(self.datalen)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if ford_velodyne_t in parents: return 0
        tmphash = (0xb6befe08f6d416d3) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ford_velodyne_t._packed_fingerprint is None:
            ford_velodyne_t._packed_fingerprint = struct.pack(">Q", ford_velodyne_t._get_hash_recursive([]))
        return ford_velodyne_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

