"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class lq_modem_t(object):
    __slots__ = ["utime", "time", "lat", "lon", "heading", "roll", "pitch", "bearing", "slantRange", "ping", "messageType"]

    FIX = 0
    PING = 1
    ABORT = 2
    GOTO = 3

    def __init__(self):
        self.utime = 0
        self.time = 0.0
        self.lat = 0.0
        self.lon = 0.0
        self.heading = 0.0
        self.roll = 0.0
        self.pitch = 0.0
        self.bearing = 0.0
        self.slantRange = 0.0
        self.ping = 0
        self.messageType = 0

    def encode(self):
        buf = BytesIO()
        buf.write(lq_modem_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qddddddddib", self.utime, self.time, self.lat, self.lon, self.heading, self.roll, self.pitch, self.bearing, self.slantRange, self.ping, self.messageType))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lq_modem_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lq_modem_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = lq_modem_t()
        self.utime, self.time, self.lat, self.lon, self.heading, self.roll, self.pitch, self.bearing, self.slantRange, self.ping, self.messageType = struct.unpack(">qddddddddib", buf.read(77))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if lq_modem_t in parents: return 0
        tmphash = (0x7429957d5d0b6da6) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if lq_modem_t._packed_fingerprint is None:
            lq_modem_t._packed_fingerprint = struct.pack(">Q", lq_modem_t._get_hash_recursive([]))
        return lq_modem_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

