"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class micron_ping_t(object):
    __slots__ = ["utime", "count", "range", "gain", "slope", "AD_interval", "left_limit", "right_limit", "angle", "range_resolution", "num_bins", "bins"]

    def __init__(self):
        self.utime = 0
        self.count = 0
        self.range = 0.0
        self.gain = 0.0
        self.slope = 0.0
        self.AD_interval = 0.0
        self.left_limit = 0.0
        self.right_limit = 0.0
        self.angle = 0.0
        self.range_resolution = 0.0
        self.num_bins = 0
        self.bins = ""

    def encode(self):
        buf = BytesIO()
        buf.write(micron_ping_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qiddddddddh", self.utime, self.count, self.range, self.gain, self.slope, self.AD_interval, self.left_limit, self.right_limit, self.angle, self.range_resolution, self.num_bins))
        buf.write(bytearray(self.bins[:self.num_bins]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != micron_ping_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return micron_ping_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = micron_ping_t()
        self.utime, self.count, self.range, self.gain, self.slope, self.AD_interval, self.left_limit, self.right_limit, self.angle, self.range_resolution, self.num_bins = struct.unpack(">qiddddddddh", buf.read(78))
        self.bins = buf.read(self.num_bins)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if micron_ping_t in parents: return 0
        tmphash = (0x167d5c1fc97f6a64) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if micron_ping_t._packed_fingerprint is None:
            micron_ping_t._packed_fingerprint = struct.pack(">Q", micron_ping_t._get_hash_recursive([]))
        return micron_ping_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

