"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class mocap_t(object):
    __slots__ = ["utime", "xyzrph", "residual", "valid"]

    def __init__(self):
        self.utime = 0
        self.xyzrph = [ 0.0 for dim0 in range(6) ]
        self.residual = 0.0
        self.valid = 0

    def encode(self):
        buf = BytesIO()
        buf.write(mocap_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        buf.write(struct.pack('>6d', *self.xyzrph[:6]))
        buf.write(struct.pack(">db", self.residual, self.valid))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != mocap_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return mocap_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = mocap_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.xyzrph = struct.unpack('>6d', buf.read(48))
        self.residual, self.valid = struct.unpack(">db", buf.read(9))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if mocap_t in parents: return 0
        tmphash = (0x4d3d64aa6acbfcd9) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if mocap_t._packed_fingerprint is None:
            mocap_t._packed_fingerprint = struct.pack(">Q", mocap_t._get_hash_recursive([]))
        return mocap_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

