"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class parosci_t(object):
    __slots__ = ["utime", "raw", "depth"]

    def __init__(self):
        self.utime = 0
        self.raw = 0.0
        self.depth = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(parosci_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qdd", self.utime, self.raw, self.depth))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != parosci_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return parosci_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = parosci_t()
        self.utime, self.raw, self.depth = struct.unpack(">qdd", buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if parosci_t in parents: return 0
        tmphash = (0x5038b7cd613298ab) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if parosci_t._packed_fingerprint is None:
            parosci_t._packed_fingerprint = struct.pack(">Q", parosci_t._get_hash_recursive([]))
        return parosci_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

