"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class relay_t(object):
    __slots__ = ["label", "group", "state", "exclude_all"]

    def __init__(self):
        self.label = ""
        self.group = ""
        self.state = False
        self.exclude_all = False

    def encode(self):
        buf = BytesIO()
        buf.write(relay_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __label_encoded = self.label.encode('utf-8')
        buf.write(struct.pack('>I', len(__label_encoded)+1))
        buf.write(__label_encoded)
        buf.write(b"\0")
        __group_encoded = self.group.encode('utf-8')
        buf.write(struct.pack('>I', len(__group_encoded)+1))
        buf.write(__group_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">bb", self.state, self.exclude_all))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != relay_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return relay_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = relay_t()
        __label_len = struct.unpack('>I', buf.read(4))[0]
        self.label = buf.read(__label_len)[:-1].decode('utf-8', 'replace')
        __group_len = struct.unpack('>I', buf.read(4))[0]
        self.group = buf.read(__group_len)[:-1].decode('utf-8', 'replace')
        self.state = bool(struct.unpack('b', buf.read(1))[0])
        self.exclude_all = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if relay_t in parents: return 0
        tmphash = (0xda84521184f3fc57) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if relay_t._packed_fingerprint is None:
            relay_t._packed_fingerprint = struct.pack(">Q", relay_t._get_hash_recursive([]))
        return relay_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

