"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class rmd1_t(object):
    __slots__ = ["utime", "voltage"]

    def __init__(self):
        self.utime = 0
        self.voltage = 0

    def encode(self):
        buf = BytesIO()
        buf.write(rmd1_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.utime, self.voltage))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != rmd1_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return rmd1_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = rmd1_t()
        self.utime, self.voltage = struct.unpack(">qi", buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if rmd1_t in parents: return 0
        tmphash = (0xc436ca2c85caf764) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if rmd1_t._packed_fingerprint is None:
            rmd1_t._packed_fingerprint = struct.pack(">Q", rmd1_t._get_hash_recursive([]))
        return rmd1_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

