"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class rph_t(object):
    __slots__ = ["utime", "rph"]

    def __init__(self):
        self.utime = 0
        self.rph = [ 0.0 for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(rph_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        buf.write(struct.pack('>3d', *self.rph[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != rph_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return rph_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = rph_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.rph = struct.unpack('>3d', buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if rph_t in parents: return 0
        tmphash = (0xb9fac93d4d2a41af) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if rph_t._packed_fingerprint is None:
            rph_t._packed_fingerprint = struct.pack(">Q", rph_t._get_hash_recursive([]))
        return rph_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

