"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class simrad_em3000_format6_t(object):
    __slots__ = ["utime", "data_time", "r", "p", "h", "heave"]

    def __init__(self):
        self.utime = 0
        self.data_time = 0
        self.r = 0.0
        self.p = 0.0
        self.h = 0.0
        self.heave = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(simrad_em3000_format6_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qiffff", self.utime, self.data_time, self.r, self.p, self.h, self.heave))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != simrad_em3000_format6_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return simrad_em3000_format6_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = simrad_em3000_format6_t()
        self.utime, self.data_time, self.r, self.p, self.h, self.heave = struct.unpack(">qiffff", buf.read(28))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if simrad_em3000_format6_t in parents: return 0
        tmphash = (0xd332aed7220fcb19) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if simrad_em3000_format6_t._packed_fingerprint is None:
            simrad_em3000_format6_t._packed_fingerprint = struct.pack(">Q", simrad_em3000_format6_t._get_hash_recursive([]))
        return simrad_em3000_format6_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

