"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class spacenav_t(object):
    __slots__ = ["x", "y", "z", "rot_x", "rot_y", "rot_z"]

    def __init__(self):
        self.x = 0
        self.y = 0
        self.z = 0
        self.rot_x = 0
        self.rot_y = 0
        self.rot_z = 0

    def encode(self):
        buf = BytesIO()
        buf.write(spacenav_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">iiiiii", self.x, self.y, self.z, self.rot_x, self.rot_y, self.rot_z))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != spacenav_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return spacenav_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = spacenav_t()
        self.x, self.y, self.z, self.rot_x, self.rot_y, self.rot_z = struct.unpack(">iiiiii", buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if spacenav_t in parents: return 0
        tmphash = (0xe4afcbbf6f6bba4) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if spacenav_t._packed_fingerprint is None:
            spacenav_t._packed_fingerprint = struct.pack(">Q", spacenav_t._get_hash_recursive([]))
        return spacenav_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

