"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class sts_spec_t(object):
    __slots__ = ["timestamp", "numSamples", "id", "specData", "intTime", "boardTemp", "detectTemp", "newTemps"]

    def __init__(self):
        self.timestamp = 0
        self.numSamples = 0
        self.id = ""
        self.specData = []
        self.intTime = 0
        self.boardTemp = 0.0
        self.detectTemp = 0.0
        self.newTemps = False

    def encode(self):
        buf = BytesIO()
        buf.write(sts_spec_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qh", self.timestamp, self.numSamples))
        __id_encoded = self.id.encode('utf-8')
        buf.write(struct.pack('>I', len(__id_encoded)+1))
        buf.write(__id_encoded)
        buf.write(b"\0")
        buf.write(struct.pack('>%dh' % self.numSamples, *self.specData[:self.numSamples]))
        buf.write(struct.pack(">hffb", self.intTime, self.boardTemp, self.detectTemp, self.newTemps))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != sts_spec_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return sts_spec_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = sts_spec_t()
        self.timestamp, self.numSamples = struct.unpack(">qh", buf.read(10))
        __id_len = struct.unpack('>I', buf.read(4))[0]
        self.id = buf.read(__id_len)[:-1].decode('utf-8', 'replace')
        self.specData = struct.unpack('>%dh' % self.numSamples, buf.read(self.numSamples * 2))
        self.intTime, self.boardTemp, self.detectTemp = struct.unpack(">hff", buf.read(10))
        self.newTemps = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if sts_spec_t in parents: return 0
        tmphash = (0xaaa99c400d19e03) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if sts_spec_t._packed_fingerprint is None:
            sts_spec_t._packed_fingerprint = struct.pack(">Q", sts_spec_t._get_hash_recursive([]))
        return sts_spec_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

