"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class subsonus_ahrs_t(object):
    __slots__ = ["utime", "acc", "gyro", "mag", "internal_temp", "pressure_depth", "water_temp", "sos"]

    def __init__(self):
        self.utime = 0
        self.acc = [ 0.0 for dim0 in range(3) ]
        self.gyro = [ 0.0 for dim0 in range(3) ]
        self.mag = [ 0.0 for dim0 in range(3) ]
        self.internal_temp = 0.0
        self.pressure_depth = 0.0
        self.water_temp = 0.0
        self.sos = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(subsonus_ahrs_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        buf.write(struct.pack('>3f', *self.acc[:3]))
        buf.write(struct.pack('>3f', *self.gyro[:3]))
        buf.write(struct.pack('>3f', *self.mag[:3]))
        buf.write(struct.pack(">ffff", self.internal_temp, self.pressure_depth, self.water_temp, self.sos))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != subsonus_ahrs_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return subsonus_ahrs_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = subsonus_ahrs_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.acc = struct.unpack('>3f', buf.read(12))
        self.gyro = struct.unpack('>3f', buf.read(12))
        self.mag = struct.unpack('>3f', buf.read(12))
        self.internal_temp, self.pressure_depth, self.water_temp, self.sos = struct.unpack(">ffff", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if subsonus_ahrs_t in parents: return 0
        tmphash = (0x951c122102c6ec42) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if subsonus_ahrs_t._packed_fingerprint is None:
            subsonus_ahrs_t._packed_fingerprint = struct.pack(">Q", subsonus_ahrs_t._get_hash_recursive([]))
        return subsonus_ahrs_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

