"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class tcm_t(object):
    __slots__ = ["utime", "heading", "roll", "pitch", "temperature"]

    def __init__(self):
        self.utime = 0
        self.heading = 0.0
        self.roll = 0.0
        self.pitch = 0.0
        self.temperature = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(tcm_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qdddd", self.utime, self.heading, self.roll, self.pitch, self.temperature))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != tcm_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return tcm_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = tcm_t()
        self.utime, self.heading, self.roll, self.pitch, self.temperature = struct.unpack(">qdddd", buf.read(40))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if tcm_t in parents: return 0
        tmphash = (0xb81589a4d7b3a49e) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if tcm_t._packed_fingerprint is None:
            tcm_t._packed_fingerprint = struct.pack(">Q", tcm_t._get_hash_recursive([]))
        return tcm_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

