"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class usbl_fix_t(object):
    __slots__ = ["utime", "remote_id", "target_x", "target_y", "target_z", "latitude", "longitude", "depth", "accuracy", "ship_latitude", "ship_longitude", "ship_roll", "ship_pitch", "ship_heading"]

    def __init__(self):
        self.utime = 0
        self.remote_id = 0
        self.target_x = 0.0
        self.target_y = 0.0
        self.target_z = 0.0
        self.latitude = 0.0
        self.longitude = 0.0
        self.depth = 0.0
        self.accuracy = 0.0
        self.ship_latitude = 0.0
        self.ship_longitude = 0.0
        self.ship_roll = 0.0
        self.ship_pitch = 0.0
        self.ship_heading = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(usbl_fix_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qidddddddddfff", self.utime, self.remote_id, self.target_x, self.target_y, self.target_z, self.latitude, self.longitude, self.depth, self.accuracy, self.ship_latitude, self.ship_longitude, self.ship_roll, self.ship_pitch, self.ship_heading))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != usbl_fix_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return usbl_fix_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = usbl_fix_t()
        self.utime, self.remote_id, self.target_x, self.target_y, self.target_z, self.latitude, self.longitude, self.depth, self.accuracy, self.ship_latitude, self.ship_longitude, self.ship_roll, self.ship_pitch, self.ship_heading = struct.unpack(">qidddddddddfff", buf.read(96))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if usbl_fix_t in parents: return 0
        tmphash = (0x6a07fc065eb1f54b) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if usbl_fix_t._packed_fingerprint is None:
            usbl_fix_t._packed_fingerprint = struct.pack(">Q", usbl_fix_t._get_hash_recursive([]))
        return usbl_fix_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

