"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class uvc_omw_t(object):
    __slots__ = ["utime", "latitude", "longitude", "depth1", "depth2", "max_pitch", "speed", "park_time"]

    def __init__(self):
        self.utime = 0
        self.latitude = 0.0
        self.longitude = 0.0
        self.depth1 = 0.0
        self.depth2 = 0.0
        self.max_pitch = 0.0
        self.speed = 0.0
        self.park_time = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(uvc_omw_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qddddddd", self.utime, self.latitude, self.longitude, self.depth1, self.depth2, self.max_pitch, self.speed, self.park_time))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != uvc_omw_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return uvc_omw_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = uvc_omw_t()
        self.utime, self.latitude, self.longitude, self.depth1, self.depth2, self.max_pitch, self.speed, self.park_time = struct.unpack(">qddddddd", buf.read(64))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if uvc_omw_t in parents: return 0
        tmphash = (0x58d245cce0be3b0f) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if uvc_omw_t._packed_fingerprint is None:
            uvc_omw_t._packed_fingerprint = struct.pack(">Q", uvc_omw_t._get_hash_recursive([]))
        return uvc_omw_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

