"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class uvc_omload_t(object):
    __slots__ = ["directory_name", "msg_flag"]

    def __init__(self):
        self.directory_name = ""
        self.msg_flag = 0

    def encode(self):
        buf = BytesIO()
        buf.write(uvc_omload_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __directory_name_encoded = self.directory_name.encode('utf-8')
        buf.write(struct.pack('>I', len(__directory_name_encoded)+1))
        buf.write(__directory_name_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">i", self.msg_flag))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != uvc_omload_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return uvc_omload_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = uvc_omload_t()
        __directory_name_len = struct.unpack('>I', buf.read(4))[0]
        self.directory_name = buf.read(__directory_name_len)[:-1].decode('utf-8', 'replace')
        self.msg_flag = struct.unpack(">i", buf.read(4))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if uvc_omload_t in parents: return 0
        tmphash = (0xe220d0f438611b5) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if uvc_omload_t._packed_fingerprint is None:
            uvc_omload_t._packed_fingerprint = struct.pack(">Q", uvc_omload_t._get_hash_recursive([]))
        return uvc_omload_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

