"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class vector_t(object):
    __slots__ = ["utime", "r", "p", "h"]

    def __init__(self):
        self.utime = 0
        self.r = 0.0
        self.p = 0.0
        self.h = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(vector_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qddd", self.utime, self.r, self.p, self.h))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != vector_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return vector_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = vector_t()
        self.utime, self.r, self.p, self.h = struct.unpack(">qddd", buf.read(32))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if vector_t in parents: return 0
        tmphash = (0x9d586387a6e53e23) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if vector_t._packed_fingerprint is None:
            vector_t._packed_fingerprint = struct.pack(">Q", vector_t._get_hash_recursive([]))
        return vector_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

