"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class ysi_t(object):
    __slots__ = ["utime", "temperature", "depth", "turbidity", "chlorophyl", "conductivity", "oxygen", "battery", "salinity"]

    def __init__(self):
        self.utime = 0
        self.temperature = 0.0
        self.depth = 0.0
        self.turbidity = 0.0
        self.chlorophyl = 0.0
        self.conductivity = 0.0
        self.oxygen = 0.0
        self.battery = 0.0
        self.salinity = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(ysi_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qdddddddd", self.utime, self.temperature, self.depth, self.turbidity, self.chlorophyl, self.conductivity, self.oxygen, self.battery, self.salinity))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ysi_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ysi_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ysi_t()
        self.utime, self.temperature, self.depth, self.turbidity, self.chlorophyl, self.conductivity, self.oxygen, self.battery, self.salinity = struct.unpack(">qdddddddd", buf.read(72))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if ysi_t in parents: return 0
        tmphash = (0x58dce4ba7b05ea0c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ysi_t._packed_fingerprint is None:
            ysi_t._packed_fingerprint = struct.pack(">Q", ysi_t._get_hash_recursive([]))
        return ysi_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

