"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class asv_torqeedo_motor_command_t(object):
    __slots__ = ["utime", "command_speed", "enabled"]

    def __init__(self):
        self.utime = 0
        self.command_speed = 0
        self.enabled = False

    def encode(self):
        buf = BytesIO()
        buf.write(asv_torqeedo_motor_command_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qhb", self.utime, self.command_speed, self.enabled))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != asv_torqeedo_motor_command_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return asv_torqeedo_motor_command_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = asv_torqeedo_motor_command_t()
        self.utime, self.command_speed = struct.unpack(">qh", buf.read(10))
        self.enabled = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if asv_torqeedo_motor_command_t in parents: return 0
        tmphash = (0xc27d9018552a9923) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if asv_torqeedo_motor_command_t._packed_fingerprint is None:
            asv_torqeedo_motor_command_t._packed_fingerprint = struct.pack(">Q", asv_torqeedo_motor_command_t._get_hash_recursive([]))
        return asv_torqeedo_motor_command_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

