"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class auv_image_stats_t(object):
    __slots__ = ["utime", "max_pixel_value", "min_pixel_value", "mean_pixel_value", "exposure_percentage", "exp_time", "image_name"]

    def __init__(self):
        self.utime = 0
        self.max_pixel_value = 0
        self.min_pixel_value = 0
        self.mean_pixel_value = 0
        self.exposure_percentage = 0
        self.exp_time = 0
        self.image_name = ""

    def encode(self):
        buf = BytesIO()
        buf.write(auv_image_stats_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qiiiii", self.utime, self.max_pixel_value, self.min_pixel_value, self.mean_pixel_value, self.exposure_percentage, self.exp_time))
        __image_name_encoded = self.image_name.encode('utf-8')
        buf.write(struct.pack('>I', len(__image_name_encoded)+1))
        buf.write(__image_name_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != auv_image_stats_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return auv_image_stats_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = auv_image_stats_t()
        self.utime, self.max_pixel_value, self.min_pixel_value, self.mean_pixel_value, self.exposure_percentage, self.exp_time = struct.unpack(">qiiiii", buf.read(28))
        __image_name_len = struct.unpack('>I', buf.read(4))[0]
        self.image_name = buf.read(__image_name_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if auv_image_stats_t in parents: return 0
        tmphash = (0x3a2f24a7b11a705c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if auv_image_stats_t._packed_fingerprint is None:
            auv_image_stats_t._packed_fingerprint = struct.pack(">Q", auv_image_stats_t._get_hash_recursive([]))
        return auv_image_stats_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

