"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class auv_relay_t(object):
    __slots__ = ["utime", "channel", "state"]

    def __init__(self):
        self.utime = 0
        self.channel = ""
        self.state = 0

    def encode(self):
        buf = BytesIO()
        buf.write(auv_relay_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        __channel_encoded = self.channel.encode('utf-8')
        buf.write(struct.pack('>I', len(__channel_encoded)+1))
        buf.write(__channel_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">b", self.state))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != auv_relay_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return auv_relay_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = auv_relay_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        __channel_len = struct.unpack('>I', buf.read(4))[0]
        self.channel = buf.read(__channel_len)[:-1].decode('utf-8', 'replace')
        self.state = struct.unpack(">b", buf.read(1))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if auv_relay_t in parents: return 0
        tmphash = (0x98773af2b4e531c6) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if auv_relay_t._packed_fingerprint is None:
            auv_relay_t._packed_fingerprint = struct.pack(">Q", auv_relay_t._get_hash_recursive([]))
        return auv_relay_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

