"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class auv_sirius_summary_t(object):
    __slots__ = ["utime", "time", "x", "y", "altitude", "depth", "heading", "goal_id", "percent_charge", "num_images"]

    def __init__(self):
        self.utime = 0
        self.time = 0.0
        self.x = 0.0
        self.y = 0.0
        self.altitude = 0.0
        self.depth = 0.0
        self.heading = 0.0
        self.goal_id = 0
        self.percent_charge = 0.0
        self.num_images = 0

    def encode(self):
        buf = BytesIO()
        buf.write(auv_sirius_summary_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qddddddidi", self.utime, self.time, self.x, self.y, self.altitude, self.depth, self.heading, self.goal_id, self.percent_charge, self.num_images))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != auv_sirius_summary_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return auv_sirius_summary_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = auv_sirius_summary_t()
        self.utime, self.time, self.x, self.y, self.altitude, self.depth, self.heading, self.goal_id, self.percent_charge, self.num_images = struct.unpack(">qddddddidi", buf.read(72))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if auv_sirius_summary_t in parents: return 0
        tmphash = (0xc5db2370546c040e) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if auv_sirius_summary_t._packed_fingerprint is None:
            auv_sirius_summary_t._packed_fingerprint = struct.pack(">Q", auv_sirius_summary_t._get_hash_recursive([]))
        return auv_sirius_summary_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

