"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class auv_sirius_motor_status_t(object):
    __slots__ = ["utime", "thruster_num", "rpm", "voltage", "current", "temp"]

    def __init__(self):
        self.utime = 0
        self.thruster_num = 0
        self.rpm = 0.0
        self.voltage = 0.0
        self.current = 0.0
        self.temp = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(auv_sirius_motor_status_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qidddd", self.utime, self.thruster_num, self.rpm, self.voltage, self.current, self.temp))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != auv_sirius_motor_status_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return auv_sirius_motor_status_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = auv_sirius_motor_status_t()
        self.utime, self.thruster_num, self.rpm, self.voltage, self.current, self.temp = struct.unpack(">qidddd", buf.read(44))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if auv_sirius_motor_status_t in parents: return 0
        tmphash = (0xc1001878eabe4e78) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if auv_sirius_motor_status_t._packed_fingerprint is None:
            auv_sirius_motor_status_t._packed_fingerprint = struct.pack(">Q", auv_sirius_motor_status_t._get_hash_recursive([]))
        return auv_sirius_motor_status_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

