"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class auv_path_response_t(object):
    __slots__ = ["utime", "goal_id", "are_we_there_yet", "distance"]

    def __init__(self):
        self.utime = 0
        self.goal_id = 0
        self.are_we_there_yet = 0
        self.distance = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(auv_path_response_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qibd", self.utime, self.goal_id, self.are_we_there_yet, self.distance))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != auv_path_response_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return auv_path_response_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = auv_path_response_t()
        self.utime, self.goal_id, self.are_we_there_yet, self.distance = struct.unpack(">qibd", buf.read(21))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if auv_path_response_t in parents: return 0
        tmphash = (0xbeface1033d4a751) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if auv_path_response_t._packed_fingerprint is None:
            auv_path_response_t._packed_fingerprint = struct.pack(">Q", auv_path_response_t._get_hash_recursive([]))
        return auv_path_response_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

