"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class auv_occmap_element_t(object):
    __slots__ = ["x", "y", "z", "timestamp", "votes"]

    def __init__(self):
        self.x = 0.0
        self.y = 0.0
        self.z = 0.0
        self.timestamp = 0.0
        self.votes = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(auv_occmap_element_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ddddd", self.x, self.y, self.z, self.timestamp, self.votes))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != auv_occmap_element_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return auv_occmap_element_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = auv_occmap_element_t()
        self.x, self.y, self.z, self.timestamp, self.votes = struct.unpack(">ddddd", buf.read(40))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if auv_occmap_element_t in parents: return 0
        tmphash = (0x273b9dc4022c63c2) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if auv_occmap_element_t._packed_fingerprint is None:
            auv_occmap_element_t._packed_fingerprint = struct.pack(">Q", auv_occmap_element_t._get_hash_recursive([]))
        return auv_occmap_element_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

