"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class auv_iver_motor_command_t(object):
    __slots__ = ["utime", "top", "bottom", "port", "starboard", "main", "source"]

    AUTO = 0
    REMOTE = 1
    RCZERO = 2
    RCRELEASE = 3

    def __init__(self):
        self.utime = 0
        self.top = 0.0
        self.bottom = 0.0
        self.port = 0.0
        self.starboard = 0.0
        self.main = 0.0
        self.source = 0

    def encode(self):
        buf = BytesIO()
        buf.write(auv_iver_motor_command_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qdddddh", self.utime, self.top, self.bottom, self.port, self.starboard, self.main, self.source))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != auv_iver_motor_command_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return auv_iver_motor_command_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = auv_iver_motor_command_t()
        self.utime, self.top, self.bottom, self.port, self.starboard, self.main, self.source = struct.unpack(">qdddddh", buf.read(50))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if auv_iver_motor_command_t in parents: return 0
        tmphash = (0x4a64be70c7f19243) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if auv_iver_motor_command_t._packed_fingerprint is None:
            auv_iver_motor_command_t._packed_fingerprint = struct.pack(">Q", auv_iver_motor_command_t._get_hash_recursive([]))
        return auv_iver_motor_command_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

