"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class auv_nga_motor_command_t(object):
    __slots__ = ["utime", "vert_fore", "vert_aft", "lat_fore", "lat_aft", "tail_thruster", "tail_rudder", "tail_elevator"]

    def __init__(self):
        self.utime = 0
        self.vert_fore = 0.0
        self.vert_aft = 0.0
        self.lat_fore = 0.0
        self.lat_aft = 0.0
        self.tail_thruster = 0.0
        self.tail_rudder = 0.0
        self.tail_elevator = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(auv_nga_motor_command_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qddddddd", self.utime, self.vert_fore, self.vert_aft, self.lat_fore, self.lat_aft, self.tail_thruster, self.tail_rudder, self.tail_elevator))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != auv_nga_motor_command_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return auv_nga_motor_command_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = auv_nga_motor_command_t()
        self.utime, self.vert_fore, self.vert_aft, self.lat_fore, self.lat_aft, self.tail_thruster, self.tail_rudder, self.tail_elevator = struct.unpack(">qddddddd", buf.read(64))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if auv_nga_motor_command_t in parents: return 0
        tmphash = (0x160748e0823bbe4f) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if auv_nga_motor_command_t._packed_fingerprint is None:
            auv_nga_motor_command_t._packed_fingerprint = struct.pack(">Q", auv_nga_motor_command_t._get_hash_recursive([]))
        return auv_nga_motor_command_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

