"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class ship_status_t(object):
    __slots__ = ["utime", "ship_id", "name", "heading", "roll", "pitch", "latitude", "longitude"]

    def __init__(self):
        self.utime = 0
        self.ship_id = 0
        self.name = ""
        self.heading = 0.0
        self.roll = 0.0
        self.pitch = 0.0
        self.latitude = 0.0
        self.longitude = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(ship_status_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qb", self.utime, self.ship_id))
        __name_encoded = self.name.encode('utf-8')
        buf.write(struct.pack('>I', len(__name_encoded)+1))
        buf.write(__name_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">ddddd", self.heading, self.roll, self.pitch, self.latitude, self.longitude))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ship_status_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ship_status_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ship_status_t()
        self.utime, self.ship_id = struct.unpack(">qb", buf.read(9))
        __name_len = struct.unpack('>I', buf.read(4))[0]
        self.name = buf.read(__name_len)[:-1].decode('utf-8', 'replace')
        self.heading, self.roll, self.pitch, self.latitude, self.longitude = struct.unpack(">ddddd", buf.read(40))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if ship_status_t in parents: return 0
        tmphash = (0x14db8fd79f471827) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ship_status_t._packed_fingerprint is None:
            ship_status_t._packed_fingerprint = struct.pack(">Q", ship_status_t._get_hash_recursive([]))
        return ship_status_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

