"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class wam_v_control_t(object):
    __slots__ = ["utime", "run_mode", "heading", "vx"]

    STOP = 0
    RUN = 1

    def __init__(self):
        self.utime = 0
        self.run_mode = 0
        self.heading = 0.0
        self.vx = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(wam_v_control_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qbdd", self.utime, self.run_mode, self.heading, self.vx))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != wam_v_control_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return wam_v_control_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = wam_v_control_t()
        self.utime, self.run_mode, self.heading, self.vx = struct.unpack(">qbdd", buf.read(25))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if wam_v_control_t in parents: return 0
        tmphash = (0xd6b639ad53c535ca) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if wam_v_control_t._packed_fingerprint is None:
            wam_v_control_t._packed_fingerprint = struct.pack(">Q", wam_v_control_t._get_hash_recursive([]))
        return wam_v_control_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

